FROM python:3.6-alpine

RUN adduser -D wordCountApp

WORKDIR /home/wordCountApp

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn

COPY app app
COPY wordCount.py config.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP wordCount.py

RUN chown -R wordCountApp:wordCountApp ./
USER WordCountApp

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]